######################################################
###                                                ###
###               HOME ASSISTANT THEMES            ###
###                                                ###
######################################################

- id: hass_theme
  alias: hass_theme
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.hass_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_theme.state }}"

######################################################
###                                                ###
###               CHANGE THEME AT NIGHT            ###
###                                                ###
######################################################

#alias: 'Set dark theme for the night'
#  initial_state: True
#  trigger:
#    - platform: time
#      at: '21:00'
#  action:
#    - service: frontend.set_theme
#      data:
#        name: night