####################################################
#                                                  #
#                     Cameras                      #
#                                                  #
####################################################

######## Weather Underground live map 
- platform: generic
  name: Weather Radar
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=RAX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25453232&lat=0&lon=0&label=you

######### Rpi Security Camera 1
- platform: rpi_camera
  name: SecCam_1
  image_width: 640
  image_height: 480
  image_quality: 7
  image_rotation: 0
  timelapse: 1000
  horizontal_flip: 0
  vertical_flip: 0
  file_path: /home/homeassistant/camera