####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################
homeassistant:
  customize: !include customize.yaml
  elevation: 809
  latitude: !secret latitude
  longitude: !secret longitude
  name: "Our Home"
  time_zone: America/New_York
  unit_system: imperial
  whitelist_external_dirs: /home/homeassistant/camera

####################################################
#                                                  #
#                 Included files                   #
#                                                  #
####################################################
sensor: !include sensors.yaml
media_player: !include media_player.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
mqtt: !include mqtt.yaml
camera: !include camera.yaml
####################################################
#introduction:
frontend:
config:
updater:
discovery:
conversation:
history:
logbook:
map:
sun:
###################################################
tts:
  - platform: google

cloud:

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True

