######################################################
###                                                ###
###                  HOME ASSISTANT                ###
###                                                ###
######################################################

homeassistant:
  customize: !include customize.yaml
  elevation: 809
  latitude: !secret latitude
  longitude: !secret longitude
  name: "Our Home"
  time_zone: America/New_York
  unit_system: imperial
# introduction:

frontend:
  themes: !include_dir_merge_named themes/
config:
updater:
discovery:
  ignore:
    - samsung_tv
conversation:
history:
logbook:
map:
sun:

######################################################
###                                                ###
###                  INCLUDE FILES                 ###
###                                                ###
######################################################

sensor: !include sensors.yaml
media_player: !include media_player.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
mqtt: !include mqtt.yaml
camera: !include camera.yaml
panel_iframe: !include iframe.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml

######################################################
###                                                ###
###                  TEXT TO SPEECH                ###
###                                                ###
######################################################

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

cloud:

######################################################
###                                                ###
###                      LOGGING                   ###
###                                                ###
######################################################

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

######################################################
###                                                ###
###                     WEB ACCESS                 ###
###                                                ###
######################################################

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True

