######################################################
###                                                ###
###          DEVICE TRACKER PRESENCE DETECT        ###
###                                                ###
######################################################

- platform: linksys_smart
  host: 192.168.240.1
  username: root
  password: CaudlesOn!y
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False

- platform: owntracks
  max_gps_accuracy: 20
  mqtt_topic: "owntracks/#"
  track_new_devices: yes

- platform: nmap_tracker
  hosts:
    - 192.168.240.57
    - 192.168.240.61
    - 192.168.240.62
  interval_seconds: 30
