####################################################
#                                                  #
#                   Media_Players                  #
#                                                  #
####################################################

- platform: spotify
  name: Spotify
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

#- platform: samsungtv
#  host: !secret samsung_id
#  name: Samsung Smart TV
#  mac: 68:27:37:C9:80:FD
#  SCAN_INTERVAL: 20

#- platform: vlc
