######################################################
###                                                ###
###                   NOTIFICATIONS                ###
###                                                ###
######################################################

- platform: xmpp
  name: jabber
  sender: !secret xmpp_username
  password: !secret xmpp_password
  recipient: C17H12ClN5O2@kode.im

#- platform: pushbullet
#    name: paulus
#    api_key: ABCDEFG