######################################################
#                                                    #
#               Home Assistant Sensors               #
#                                                    #
######################################################

######################################################
###                                                ###
###                      WEATHER                   ###
###                                                ###
######################################################

- platform: yr

- platform: wunderground
  name: 'Weather'
  api_key: !secret forecast_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - feelslike_f
    - heat_index_f
    - elevation
    - precip_1hr_in
    - precip_1hr_string
    - precip_today_in
    - relative_humidity
    - temp_f
    - wind_mph

######################################################
###                                                ###
###               LIVING ROOM CLIMATE              ###
###                                                ###
######################################################

- platform: mqtt
  name: "Temperature"
  state_topic: "livingroom/sensor/temperature"
  qos: 0
  unit_of_measurment: farenheit

- platform: mqtt
  name: "Humidity"
  state_topic: "livingroom/sensor/humidity"
  qos: 0
  unit_of_measurment: "%"

######################################################
###                                                ###
###                 BANDWIDTH TEST                 ###
###                                                ###
######################################################

- platform: fastdotcom
  name: "Speedtest_1"
- platform: speedtest
  name: "Speedtest_2"
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

######################################################
###                                                ###
###                  SYSTEM MONITOR                ###
###                                                ###
######################################################

- platform: systemmonitor
  name: System Monitor
  resources:
    - type: disk_use_percent
    - type: memory_free
    - type: processor_use

######################################################
###                                                ###
###                      POOL                      ###
###                                                ###
######################################################

- platform: mqtt
  state_topic: "pool/sensor/temperature"
  name: "Pool temp"
  unit_of_measurement: "°f"
  qos: 1

######################################################
###                                                ###
###                    TIME/DATE                   ###
###                                                ###
######################################################

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'

######################################################
###                                                ###
###                    PI-HOLE                     ###
###                                                ###
######################################################

- platform: pi_hole
  host: 192.168.240.247
- platform: template
  sensors:
    pihole_queries_today:
      value_template: '{{ states.sensor.pihole.attributes.queries_today }}'
      friendly_name: 'Queries Today'
    pihole_percentage_today:
      value_template: '{{ states.sensor.pihole.attributes.percentage_today }}'
      friendly_name: 'Percentage Today'
    pihole_domains_blocked:
      value_template: '{{ states.sensor.pihole.attributes.domains_blocked }}'
      friendly_name: 'Domains Blocked'

######################################################
###                                                ###
###            LENOVO HARDWARE MONITOR             ###
###                                                ###
######################################################

- platform: openhardwaremonitor
  host: 192.168.240.53

######################################################
###                                                ###
###               PHONE BATTERY LEVEL              ###
###                                                ###
######################################################

- platform: mqtt
  state_topic: "owntracks/username/deviceid"
  name: "Phone Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

