######################################################
#                                                    #
#               Home Assistant Sensors               #
#                                                    #
######################################################

######################################################
###                                                ###
###                      WEATHER                   ###
###                                                ###
######################################################

- platform: yr

- platform: wunderground
  name: 'Weather'
  api_key: !secret forecast_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - feelslike_f
    - heat_index_f
    - elevation
    - precip_1hr_in
    - precip_1hr_string
    - precip_today_in
    - relative_humidity
    - temp_f
    - wind_mph

######################################################
###                                                ###
###               LIVING ROOM CLIMATE              ###
###                                                ###
######################################################

- platform: mqtt
  name: "Temperature"
  state_topic: "livingroom/sensor/temperature"
  qos: 0
  unit_of_measurment: farenheit

- platform: mqtt
  name: "Humidity"
  state_topic: "livingroom/sensor/humidity"
  qos: 0
  unit_of_measurment: "%"

######################################################
###                                                ###
###                 BANDWIDTH TEST                 ###
###                                                ###
######################################################

- platform: fastdotcom 
  name: "Download Speed"

######################################################
###                                                ###
###                  SYSTEM MONITOR                ###
###                                                ###
######################################################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_free
    - type: processor_use

######################################################
###                                                ###
###                      POOL                      ###
###                                                ###
######################################################

- platform: mqtt
  state_topic: "pool/sensor/temperature"
  name: "Pool temp"
  unit_of_measurement: "°f"
  qos: 1

######################################################
###                                                ###
###                    TIME/DATE                   ###
###                                                ###
######################################################

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
